### ISSUE TITLE
Definir el proyecto a realizar en la materia

### ISSUE THREAD

**Issue by hrnn** [compilerCompiler/compilerCompiler#1]
Buscar en Sicoes proyectos de sistemas.
Evitar usar proyectos pasados listados en la plataforma virtual.
Definir como equipo que proyecto de sicoes se va a trabajar.
Mostrar el proyecto al docente.

**Comment by Manu200162** [comment]
El proyecto escogido primeramente se analizo los requerimientos y si eran factibles para realizar. Luego del análisis se llego a la conclusión que era un proyecto viable.
