### ISSUE TITLE
Seleccionar y escribir los Requerimientos Funcionales y NO funcionales 

### ISSUE THREAD

**Issue by lucky1523** [compilerCompiler/compilerCompiler#14]
En la sección de descripción del proyecto, sebe debe explicar cuales serán lo requerimientos funcionales que tendremos para que luego estos estén demostrados en usos de caso y en mockups.

**Comment by Manu200162** [comment]
Luego de haber seleccionado los requerimientos funcionales, y no funcionales, se los escribieron en sus secciones correspondientes.
